version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: batch_articles_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
    networks:
      - app-network

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: multimodal_rag_app
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/
    depends_on:
      - mongodb
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge 